# Generated by Django 3.0.3 on 2020-08-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20200824_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Histories',
        ),
    ]
