# Generated by Django 3.0.3 on 2020-08-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_histories'),
    ]

    operations = [
        migrations.AddField(
            model_name='histories',
            name='cd',
            field=models.IntegerField(null=True, verbose_name='cd'),
        ),
    ]
