# Generated by Django 3.1 on 2020-08-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
