# Generated by Django 3.1 on 2020-08-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='contents',
            new_name='comment',
        ),
    ]
