# Generated by Django 3.1 on 2020-08-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20200827_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product',
            new_name='history',
        ),
    ]
