# Generated by Django 3.1 on 2020-08-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200819_1541'),
        ('membership', '0013_auto_20200827_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Histories',
            new_name='History',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
