# Generated by Django 3.1 on 2020-08-28 08:36

from django.db import migrations, models
import membership.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_auto_20200827_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000, validators=[membership.models.min_length_10_validator], verbose_name='글내용'),
        ),
    ]
