# Generated by Django 3.1 on 2020-08-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='이름')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('phone_num', models.CharField(default=0, max_length=11, verbose_name='전화번호')),
                ('point', models.IntegerField(default=0, verbose_name='마일리지')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
