# Generated by Django 3.0.8 on 2020-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200819_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='select_adr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
