# Generated by Django 3.1 on 2020-09-01 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_select_adr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='작성자')),
                ('title', models.TextField(max_length=1000, verbose_name='글제목')),
                ('contents', models.TextField(max_length=1000, verbose_name='글내용')),
                ('created_date', models.DateField(null=True, verbose_name='작성시간')),
                ('qtype', models.CharField(default='매장', max_length=15, verbose_name='문의유형')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='댓글 작성자')),
                ('text', models.TextField(max_length=1000, verbose_name='댓글 내용')),
                ('created_date', models.DateField(null=True, verbose_name='작성시간')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.post')),
            ],
        ),
    ]
