# Generated by Django 3.0.8 on 2020-08-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('kcal', models.IntegerField()),
                ('sat_fat', models.IntegerField(db_column='sat_FAT')),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('trans_fat', models.IntegerField(db_column='trans_FAT')),
                ('sodium', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('caffeine', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('chabo', models.IntegerField()),
            ],
            options={
                'db_table': 'starbucks',
                'managed': False,
            },
        ),
    ]
