# Generated by Django 3.0.8 on 2020-08-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('order', '0003_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='carts',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='수량'),
        ),
        migrations.AddField(
            model_name='carts',
            name='total',
            field=models.IntegerField(default=0, verbose_name='총가격'),
        ),
        migrations.AddField(
            model_name='carts',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
