# Generated by Django 3.0.8 on 2020-08-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_carts_cd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='user_id',
            new_name='identity',
        ),
    ]
