# Generated by Django 3.0.8 on 2020-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200819_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='category',
            field=models.CharField(max_length=20, null=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='cd',
            field=models.IntegerField(null=True, verbose_name='cd'),
        ),
    ]
