# Generated by Django 3.0.8 on 2020-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200819_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarbucksAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'starbucks_address',
                'managed': False,
            },
        ),
    ]
