# Generated by Django 3.1 on 2020-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_starbucksaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='상품명'),
        ),
    ]
